package constants

const (
	TRANSACTION_STATUS_PENDING  = "PENDING"
	TRANSACTION_STATUS_HELD     = "HELD"
	TRANSACTION_STATUS_COMPLETE = "COMPLETE"
	TRANSACTION_STATUS_FAILED   = "FAILED"
)

const (
	TRANSACTION_TYPE_DEPOSIT  = "DEPOSIT"
	TRANSACTION_TYPE_WITHDRAW = "WITHDRAW"
)
